import { ThemeProvider } from "@/components/MaterialTailwind";
import StoreProvider from "@/redux/StoreProvider";
import { Noto_Sans_Bengali } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./pages/shared/Footer";
import StickyNavbar from "./pages/shared/Navbar";

const noto_sans = Noto_Sans_Bengali({ subsets: ["latin"] });

export const headingFont = localFont({
  src: "../assets/fonts/IhtishamDeshlipi/Unicode/LiIhtishamDeshlipiUnicode-Regular.ttf",
  display: "swap",
});

export const metadata = {
  title: "ইলম কেয়ার বিডি",
  description: "Generated by create next app",
};

const theme = {
  button: {
    defaultProps: {
      color: "deep-purple",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider value={theme}>
        <body className={noto_sans.className} suppressHydrationWarning={true}>
          <StoreProvider>
            <StickyNavbar />
            {children}
            <Footer />
          </StoreProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
